### ISSUE TITLE
Git hub connectivity issue

### ISSUE THREAD

**Issue by vignesh70** [llubu/mpro#1]
Hi Team,

We are facing intermittent connectivity issue on from our desktop as well as our build server Atlassian Bamboo.

Please consider this priority and do the necessary ASAP
Regards
Vignesh M

**Comment by llubu** [comment]
I think you are on a wrong repo.

**Comment by Sonalg25** [comment]
Hi,
I am trying to run on OpenSSL 3.0.2 where it's throwing segmentation fault error. which version of OpenSSL you used?
